### ISSUE TITLE
live reload 2.0.5 not working with Electron 21.2.2 and Svelte 3.49.0

### ISSUE THREAD

**Issue by busterbogheart** [thgh/rollup-plugin-livereload#74] opened 2023-03-21 16:09 UTC
I have checked that the port is open, and it is, though I've assigned a `port` as well with no change.  I have tried `path.resolve(__dirname....` to specify directories, as well as `public`, `./public`, etc.  I've tried a `delay` config, too.

My config is the following (options removed)
```
input: ...
output: ...
plugins: 
  svelte(),
  commonjs(),
  css(),
  typescript(),
  alias(),
  resolve(),
  nodePolyfills(),
  serve(),
  livereload(),
  json(),
```

Every time still the build prints `LiveReload enabled` in green.  But there is no reload on changing css in `public` nor changes in the main app to Svelte components, for example.

I should mention we maintain two rollup builds, one is above and the other is for a worker script (which doesn't use the `livereload` plugin).

Please let me know what else I can tell you about our setup.

**Comment by jonkoops** [comment] 2023-08-07 09:06
Hi @busterbogheart, could you create a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) for this issue, perhaps as a separate repository with only the dependencies which you can reproduce this issue with? There could be many factors influencing this issue, and it's hard to tell from the description what the culprit is.

Have you taken any steps to debug this yourself? Are there messages in the browser console? Perhaps network requests that are failing?

**Comment by jonkoops** [comment] 2023-08-07 09:26
I am thinking this issue might be a duplicate of #54, but am not entirely sure.

**Closed** 2023-08-14 10:20 UTC
