### ISSUE TITLE
first start is too slow

### ISSUE THREAD

**Issue by banli17** [thgh/rollup-plugin-livereload#70] opened 2021-08-23 09:26 UTC
The first time the startup was too slow, I started several directories, and the first one took more than 30 seconds, even for one directory.

![image](https://user-images.githubusercontent.com/12556069/130423702-b33ae794-c214-43a4-89a6-bf9d05ca8efe.png)

**Comment by jdoubleu** [comment] 2022-03-29 19:39
Indeed, this doesn't look to good. My project generally takes a few seconds (~2).

Could you please provide additional information, like:
1. what does your environment look like? Node.js on Mac or Windows, inside a Docker container, etc.
2. how many files are you watching?
3. what Node.js version are you using?

Since this plugin is basically wrapping [`node-livereload`](https://github.com/napcs/node-livereload), which is [using chokidar](https://github.com/napcs/node-livereload/blob/main/lib/livereload.js#L145), it might be an issue with [chokidar](https://www.npmjs.com/package/chokidar) or Node.js itself.

**Comment by royalfig** [comment] 2023-03-14 22:10
Found this issue because I was having the same problem. 

For me, it was because I was including my `node_modules` folder in my watched files. Once I excluded them, I no longer had the slow start problem!

**Comment by jonkoops** [comment] 2023-08-07 09:31
Closing this as OP never provided more information on what the setup was that is causing this issue, making it impossible to reproduce.

**Closed by jonkoops** 2023-08-07 09:31 UTC
